### ISSUE TITLE
Missing organisation in a page causes the script to error out

### ISSUE THREAD

**Issue by betsybookwyrm** [xueyingtan/WebScrapingTute#2]
A search I ran encountered an article which apparently is missing an element from the byline, and the script errored out.

It would be great if it could handle missing data and continue scraping, perhaps by catching the AttributeError and just inserting a None/NULL for that value?

Thank you :)

Error message as follows:

```
$ scrape -q covid
Traceback (most recent call last):
  File "/home/betsy/.pyenv/versions/webscraping/bin/scrape", line 11, in <module>
    load_entry_point('scraper', 'console_scripts', 'scrape')()
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/betsy/dev/repos/dmrc/WebScrapingTute/scraper.py", line 36, in main
    row.append(article.select_one("p.byline").em.text) #organisation
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by xueyingtan** [comment]
Bug fixed in commit #5a15185
