### ISSUE TITLE
Running 'scrape' without any arguments gives an error

### ISSUE THREAD

**Issue by betsybookwyrm** [xueyingtan/WebScrapingTute#3]
If I just run `scrape` without any arguments I get an error:

```
$ scrape
Traceback (most recent call last):
  File "/home/betsy/.pyenv/versions/webscraping/bin/scrape", line 11, in <module>
    load_entry_point('scraper', 'console_scripts', 'scrape')()
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/betsy/.pyenv/versions/3.8.5/envs/webscraping/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/betsy/dev/repos/dmrc/WebScrapingTute/scraper.py", line 41, in main
    urlquery = url+soup.find('a',attrs={'rel':'next'})['href'] # get next page if there is one (Each page returns 10 article posts)
TypeError: 'NoneType' object is not subscriptable
```
It would be good if either a more meaningul error message came up so it was easier to tell what was wrong, or if the lack of query was handled some other way. Or maybe the query argument could be made compulsory.

Thanks :)

**Comment by xueyingtan** [comment]
Thanks for raising the issue. Bug fixed in commit #5a15185
